[package]
name = "tokio-cancellation-ext"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros"] }
tokio-util = "0.7"
log = "0.4"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
